version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: collabdev_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-secret}

  redis:
    image: redis:7-alpine
    container_name: collabdev_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS:-redispass}
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
